Added hostname-strict-https option
ansible-middleware/keycloak pull request #195
Opened 2024-04-17 20:58 UTC by InfoSec812

Resolves #193 

Added a new option `keycloak_quarkus_hostname_strict_https` with no default value.

If the option is set, the Jinja template for `keycloak.conf.j2` checks to see if the value is either `true` or `false` and applies it appropriately

2024-04-18 07:08 UTC, guidograzioli requested changes
just a minor change needed, thanks for the contribution

2024-04-18 07:08 UTC, guidograzioli commented on roles/keycloak_quarkus/templates/keycloak.conf.j2
> +hostname-strict-https={{ keycloak_quarkus_hostname_strict_https }}
you need `| lower` or python will emit False instead of false, which quarkus doesn't like

2024-04-18 07:08 UTC, guidograzioli commented on roles/keycloak_quarkus/templates/keycloak.conf.j2
> +hostname-strict-https={{ keycloak_quarkus_hostname_strict_https }}
plus, please add the role parameter to meta/argument_specs.yml, with `required: no` and telling in the description that it only applies when `keycloak_quarkus_frontend_url` is not set

2024-04-18 07:08 UTC, guidograzioli commented on roles/keycloak_quarkus/templates/keycloak.conf.j2
> +{% if keycloak_quarkus_hostname_strict_https -%}
`if keycloak_quarkus_hostname_strict_https is defined`

2024-04-18 17:17 UTC, InfoSec812 commented
@guidograzioli I modified it to better handle ensuring that the value is a boolean and it should address your concern as well.

2024-04-19 07:05 UTC, guidograzioli commented
Thanks for updating, but the specification for the new parameter is still needed here:
https://github.com/ansible-middleware/keycloak/blob/main/roles/keycloak_quarkus/meta/argument_specs.yml#L335

2024-04-19 13:56 UTC, InfoSec812 commented
@guidograzioli OK, I think that latest change should cover it.

Thanks!

2024-04-19 13:59 UTC, guidograzioli approved these changes
LGTM, thanks

2024-04-19 14:05 UTC, merged